# Streamlit secrets configuration
# Note: This file is for local development only
# For Streamlit Cloud deployment, add these as secrets in the Streamlit Cloud dashboard

[secrets]
GEMINI_API_KEY = "AIzaSyDIlLP1t5uCh5mniMOL-tfb9-G-DVb3t-k"
SUPABASE_URL = "https://awcyaaxbcizjrdzhhfoo.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3Y3lhYXhiY2l6anJkemhoZm9vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzQ2Mzk1MSwiZXhwIjoyMDYzMDM5OTUxfQ.CYH4c8VaeIEzYG2STSlw2KmYPQd3Scw0UhpULhVYqf0"
